export const FETCH_FEATURED_PRODUCTS = 'FETCH_FEATURED_PRODUCTS';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_PRODUCTS_FOR_SALE = 'FETCH_PRODUCTS_FOR_SALE';
export const FETCH_PRODUCTS_SOLD = 'FETCH_PRODUCTS_SOLD';
export const FETCH_PRODUCTS_SOURCED = 'FETCH_PRODUCTS_SOURCED';
export const FETCH_PRODUCTS_FROM_MAKER = 'FETCH_PRODUCTS_FROM_MAKER';

// PDP
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
export const SET_SIMILAR_PRODUCTS = 'SET_SIMILAR_PRODUCTS';
export const CLEAR_CURRENT_PRODUCT = 'CLEAR_CURRENT_PRODUCT';

// SEARCH
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const CLEAR_ACTIVE_SEARCH = 'CLEAR_ACTIVE_SEARCH';

// ADMIN
export const SET_DB_TYPE = 'SET_DB_TYPE';
export const FETCH_BUY_REQUESTS = 'FETCH_BUY_REQUESTS';
export const FETCH_CONTACT_REQUESTS = 'FETCH_CONTACT_REQUESTS';
